[package]
name = "pdp_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-ini = "0.21.1"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = {version = "1.0.122", features = ["preserve_order"]}
